export const API: string = "http://localhost:3000/api/v1"
export const KEYCLOAK_URL: string = "http://localhost:8080/auth"
export const KEYCLOAK_REALM: string = "master"
export const KEYCLOAK_CLIENT: string = "my_client"
export const KEYCLOAK_BEARER_PREFIX: string = "Bearer "
