version: '3'
services:
  mail-sender-go:
    image: daneker/mail-sender-go
    container_name: mail-sender
    ports:
      - "8082:8082"
    environment:
      - SMTP_PASSWORD=${SMTP_PASSWORD}
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=daneker
      - MONGO_INITDB_ROOT_PASSWORD=daneker
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=daneker
      - ME_CONFIG_MONGODB_ADMINPASSWORD=daneker
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}
