spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
  application:
    name: course-service
  minio:
    bucket-name: lms
    endpoint: http://127.0.0.1:9000
    access-key: minioadmin
    secret-key: minioadmin
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://172.18.0.2:5432/lms_course
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /api/v1
  port: 8083
