spring:
  data:
    mongodb:
      username: daneker
      password: daneker
      host: localhost
      port: 27017
      database: lms
      authentication-database: admin
  application:
    name: certificate-service


server:
  port: 8081
  servlet:
    context-path: /api/v1/certificate/