spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: certificate-service
          uri: http://localhost:8081/api/v1/certificate
          predicates:
            - Path=/api/v1/certificate/**
        - id: qr-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/qr-service/**
    globalcors:
      add-to-simple-url-handler-mapping: true
      corsConfigurations:
        '[/**]':
          allowedOrigins: "http://localhost:4200"
          allowedHeaders: "*"
          allowedMethods:
            - GET
            - POST
            - DELETE
            - PATCH
            - PUT
  application:
    name: api-gateway
server:
  port: 3000
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
